version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    platform: linux/amd64
    restart: on-failure
    ports:
      - 5505:5505
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tyudb99
      - MYSQL_PASSWORD=tyudb99
      - MYSQL_USER=tyu
      - MYSQL_DATABASE=dashboard_data
    expose:
      - 5505
  
  so_data:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4996:4996"
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'php_my_admin'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '800:80'
volumes:
  mariadb_data:
