version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    platform: linux/amd64
    restart: on-failure
    ports:
      - 5505:5505
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Edgehill2023
      - MYSQL_PASSWORD=Edgehill2023
      - MYSQL_USER=edgehill
      - MYSQL_DATABASE=dashboard_data

  redis:
    image: redislabs/redismod
    restart: on-failure
    container_name: redis
    ports: 
      - 6379:6379

  so_data:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4996:4996"
    depends_on:
      - mariadb
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'php_my_admin'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 5505
      UPLOAD_LIMIT: 300M
    ports:
      - '800:80'
volumes:
  mariadb_data:
